#pragma once

#include "GXDLMSObjectCollection.h"
#include "GXDLMSClock.h"
#include "GXDLMSRegister.h"
#include "GXDLMSData.h"
#include "GXDLMSAssociationLogicalName.h"

class ObisObjectModel
{
public:
    ObisObjectModel();
    ~ObisObjectModel();

    void AddBasicTestObisObjects(CGXDLMSObjectCollection& items, unsigned long serialNumber);

    void Group_Identification(CGXDLMSObjectCollection& items, unsigned long serialNumber);
    void Group_EnergyRegisters(CGXDLMSObjectCollection& items);
    void Group_TariffRegisters(CGXDLMSObjectCollection& items);
    void Group_InstantaneousValues(CGXDLMSObjectCollection& items);
    void Group_ClockObjects(CGXDLMSObjectCollection& items);
    void Group_SystemParameters(CGXDLMSObjectCollection& items);

    CGXDLMSAssociationLogicalName* AddAssociationLN(CGXDLMSObjectCollection& items, int clientSAP, int serverSAP);
    CGXDLMSClock* AddClockObject(CGXDLMSObjectCollection& items);
    CGXDLMSData* AddLogicalDeviceName(CGXDLMSObjectCollection& items, unsigned long sn);
    CGXDLMSRegister* AddActiveEnergyL1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* AddActiveEnergyL2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* AddActiveEnergyL3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* AddActiveEnergyTotal(CGXDLMSObjectCollection& items);
    CGXDLMSData* SetSerialNumber(CGXDLMSObjectCollection& items);
    CGXDLMSData* SetMeterType(CGXDLMSObjectCollection& items);
    CGXDLMSData* SetFirmwareVersion(CGXDLMSObjectCollection& items);
    CGXDLMSData* SetChecksum(CGXDLMSObjectCollection& items);
    CGXDLMSData* SetCurrentTransformerRatio(CGXDLMSObjectCollection& items);
    CGXDLMSData* SetVoltageTransformCoeff(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyImportTariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyImportTariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyImportTariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyImportTariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportTotal(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportL1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportL2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportL3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportTariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportTariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportTariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyExportTariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_3_8_0(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportTariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportTariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportTariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportTariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_4_8_0(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyTariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyTariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyTariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyTariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ1_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ1_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ1_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyQ1_Tariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyQ1_Tariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyQ1_Tariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyQ1_Tariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_Total(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_Tariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_Tariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_Tariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyExport_Q2_Tariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ3_Aminus(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyQ3_Aminus_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyQ3_Aminus_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyQ3_Aminus_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_Q3_Tariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_Q3_Tariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_Q3_Tariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_Q3_Tariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ4_Aplus(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ4_Aplus_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ4_Aplus_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImportQ4_Aplus_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_Q4_Tariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_Q4_Tariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetReactiveEnergyImport_Q4_Tariff3(CGXDLMSObjectCollection& items);    
    CGXDLMSRegister* SetReactiveEnergyImport_Q4_Tariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySplus(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySplus_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySplus_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySplus_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySminus(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySminus_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySminus_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetApparentEnergySminus_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsSum(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbs_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbs_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbs_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbs_Tariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbs_Tariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbs_Tariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbs_Tariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff_Tariff1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff_Tariff2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff_Tariff3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergyAbsDiff_Tariff4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q1_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q1_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q1_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q2_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q2_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q2_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q3_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q3_L2(CGXDLMSObjectCollection& items); 
    CGXDLMSRegister* SetActiveEnergy_Q3_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q4_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q4_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetActiveEnergy_Q4_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerImport(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerImport_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerImport_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerImport_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerExport(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerExport_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerExport_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerExport_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerImport(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerImport_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerImport_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerImport_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerExport(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerExport_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerExport_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePowerExport_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q1_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q2_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q3_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q4_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q1_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q2_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q3_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q4_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q1_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q2_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q3_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantReactivePower_Q4_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSplus(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSplus_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSplus_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSplus_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSminus(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSminus_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSminus_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantApparentPowerSminus_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsSum(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsSum_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsSum_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsSum_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsDiff(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsDiff_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsDiff_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePowerAbsDiff_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q4(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q1_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q2_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q3_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q4_L1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q1_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q2_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q3_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q4_L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q1_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q2_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q3_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantActivePower_Q4_L3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantCurrentL1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantCurrentL2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantCurrentL3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantVoltageL1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantVoltageL2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantVoltageL3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantPowerFactorL1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantPowerFactorL2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantPowerFactorL3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantFrequencyL1(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantFrequencyL2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetInstantFrequencyL3(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetPhaseAngleL1L2(CGXDLMSObjectCollection& items);
    CGXDLMSRegister* SetPhaseAngleL1L3(CGXDLMSObjectCollection& items);
    CGXDLMSClock* GetClock() const { return m_pClock; }
    CGXDLMSRegister* GetEnergyRegister() const { return m_pEnergyRegister; }

private:
    CGXDLMSClock* m_pClock = nullptr;
    CGXDLMSRegister* m_pEnergyRegister = nullptr;
};
